# Unless otherwise specified, hooks run on push only
default_stages:
  - "push"
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: .venv/bin/ruff check --force-exclude
        language: system
        types:
          - "python"
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: .venv/bin/ruff format
        language: system
        types:
          - "python"
        require_serial: true
      - id: basedpyright
        name: bpyright
        entry: .venv/bin/basedpyright
        pass_filenames: false
        language: system
        types:
          - "python"
      - id: test
        name: test
        entry: make test
        pass_filenames: false
        language: system
        types:
          - "python"
