name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup Python
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.12'

      - name: Cache Virtual Environment
        id: venv-cache
        uses: actions/cache@v3
        with:
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version}}-${{ hashFiles('pyproject.toml') }}
          path: .venv

      - name: Cache Pre-Commit
        uses: actions/cache@v3
        with:
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version}}-${{ hashFiles('.pre-commit-config.yaml') }}
          path: ~/.cache/pre-commit
          
      - name: make install
        run: make install
        # outputs.cache-hit is set by cache action after it attempts to retrieve cached data. It holds a true value
        # if the value is false it means there is no cached data available for the specific key
        if: steps.venv-cache.outputs.cache-hit != 'true'

      - name: make check
        run: make check test
